

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "address" "text" NOT NULL,
    "sequence" bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE "public"."accounts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."balances" (
    "address" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "asset_id" "text" NOT NULL,
    "amount" numeric NOT NULL
);


ALTER TABLE "public"."balances" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."block_headers" (
    "chain_id" "text" NOT NULL,
    "height" bigint NOT NULL,
    "time" timestamp with time zone DEFAULT "now"() NOT NULL,
    "last_signatures_hash" "text" NOT NULL,
    "txs_hash" "text" NOT NULL,
    "next_signers_hash" "text" NOT NULL,
    "signatures" "jsonb" NOT NULL
);


ALTER TABLE "public"."block_headers" OWNER TO "postgres";


ALTER TABLE "public"."block_headers" ALTER COLUMN "height" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."blocks_height_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE IF NOT EXISTS "public"."tx_inclusions" (
    "tx_hash" "text" DEFAULT "gen_random_uuid"() NOT NULL,
    "chain_id" "text" NOT NULL,
    "height" bigint NOT NULL
);


ALTER TABLE "public"."tx_inclusions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."txs" (
    "hash" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "body" "jsonb",
    "signature" "jsonb"
);


ALTER TABLE "public"."txs" OWNER TO "postgres";


ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("address");



ALTER TABLE ONLY "public"."balances"
    ADD CONSTRAINT "balances_pkey" PRIMARY KEY ("address", "asset_id");



ALTER TABLE ONLY "public"."block_headers"
    ADD CONSTRAINT "blocks_pkey" PRIMARY KEY ("chain_id", "height");



ALTER TABLE ONLY "public"."tx_inclusions"
    ADD CONSTRAINT "tx_inclusions_pkey" PRIMARY KEY ("tx_hash");



ALTER TABLE ONLY "public"."txs"
    ADD CONSTRAINT "txs_pkey" PRIMARY KEY ("hash");



ALTER TABLE ONLY "public"."balances"
    ADD CONSTRAINT "balances_address_fkey" FOREIGN KEY ("address") REFERENCES "public"."accounts"("address");



ALTER TABLE ONLY "public"."balances"
    ADD CONSTRAINT "balances_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "public"."coins"("id");



ALTER TABLE ONLY "public"."tx_inclusions"
    ADD CONSTRAINT "tx_inclusions_tx_hash_fkey" FOREIGN KEY ("tx_hash") REFERENCES "public"."txs"("hash");



ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."balances" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."block_headers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tx_inclusions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."txs" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."accounts" TO "anon";
GRANT ALL ON TABLE "public"."accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts" TO "service_role";



GRANT ALL ON TABLE "public"."balances" TO "anon";
GRANT ALL ON TABLE "public"."balances" TO "authenticated";
GRANT ALL ON TABLE "public"."balances" TO "service_role";



GRANT ALL ON TABLE "public"."block_headers" TO "anon";
GRANT ALL ON TABLE "public"."block_headers" TO "authenticated";
GRANT ALL ON TABLE "public"."block_headers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blocks_height_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blocks_height_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blocks_height_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tx_inclusions" TO "anon";
GRANT ALL ON TABLE "public"."tx_inclusions" TO "authenticated";
GRANT ALL ON TABLE "public"."tx_inclusions" TO "service_role";



GRANT ALL ON TABLE "public"."txs" TO "anon";
GRANT ALL ON TABLE "public"."txs" TO "authenticated";
GRANT ALL ON TABLE "public"."txs" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
