// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file modules/auth/genesis.proto (package supabase_l2_blockchain.modules.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Account } from "./account_pb";
import { file_modules_auth_account } from "./account_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/auth/genesis.proto.
 */
export const file_modules_auth_genesis: GenFile = /*@__PURE__*/
  fileDesc("Chptb2R1bGVzL2F1dGgvZ2VuZXNpcy5wcm90bxImc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5tb2R1bGVzLmF1dGgudjEiUQoMR2VuZXNpc1N0YXRlEkEKCGFjY291bnRzGAEgAygLMi8uc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5tb2R1bGVzLmF1dGgudjEuQWNjb3VudGIGcHJvdG8z", [file_modules_auth_account]);

/**
 * @generated from message supabase_l2_blockchain.modules.auth.v1.GenesisState
 */
export type GenesisState = Message<"supabase_l2_blockchain.modules.auth.v1.GenesisState"> & {
  /**
   * @generated from field: repeated supabase_l2_blockchain.modules.auth.v1.Account accounts = 1;
   */
  accounts: Account[];
};

/**
 * Describes the message supabase_l2_blockchain.modules.auth.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_modules_auth_genesis, 0);

