// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file modules/bank/genesis.proto (package supabase_l2_blockchain.modules.bank.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Balance } from "./balance_pb";
import { file_modules_bank_balance } from "./balance_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/bank/genesis.proto.
 */
export const file_modules_bank_genesis: GenFile = /*@__PURE__*/
  fileDesc("Chptb2R1bGVzL2JhbmsvZ2VuZXNpcy5wcm90bxImc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5tb2R1bGVzLmJhbmsudjEiUQoMR2VuZXNpc1N0YXRlEkEKCGJhbGFuY2VzGAEgAygLMi8uc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5tb2R1bGVzLmJhbmsudjEuQmFsYW5jZWIGcHJvdG8z", [file_modules_bank_balance]);

/**
 * @generated from message supabase_l2_blockchain.modules.bank.v1.GenesisState
 */
export type GenesisState = Message<"supabase_l2_blockchain.modules.bank.v1.GenesisState"> & {
  /**
   * @generated from field: repeated supabase_l2_blockchain.modules.bank.v1.Balance balances = 1;
   */
  balances: Balance[];
};

/**
 * Describes the message supabase_l2_blockchain.modules.bank.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_modules_bank_genesis, 0);

