// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file modules/bank/msgs.proto (package supabase_l2_blockchain.modules.bank.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Asset } from "../../core/asset_pb";
import { file_core_asset } from "../../core/asset_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/bank/msgs.proto.
 */
export const file_modules_bank_msgs: GenFile = /*@__PURE__*/
  fileDesc("Chdtb2R1bGVzL2JhbmsvbXNncy5wcm90bxImc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5tb2R1bGVzLmJhbmsudjEiagoHTXNnU2VuZBIUCgxmcm9tX2FkZHJlc3MYASABKAkSEgoKdG9fYWRkcmVzcxgCIAEoCRI1CgZhc3NldHMYAyADKAsyJS5zdXBhYmFzZV9sMl9ibG9ja2NoYWluLmNvcmUudjEuQXNzZXRiBnByb3RvMw", [file_core_asset]);

/**
 * @generated from message supabase_l2_blockchain.modules.bank.v1.MsgSend
 */
export type MsgSend = Message<"supabase_l2_blockchain.modules.bank.v1.MsgSend"> & {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress: string;

  /**
   * @generated from field: string to_address = 2;
   */
  toAddress: string;

  /**
   * @generated from field: repeated supabase_l2_blockchain.core.v1.Asset assets = 3;
   */
  assets: Asset[];
};

/**
 * Describes the message supabase_l2_blockchain.modules.bank.v1.MsgSend.
 * Use `create(MsgSendSchema)` to create a new message.
 */
export const MsgSendSchema: GenMessage<MsgSend> = /*@__PURE__*/
  messageDesc(file_modules_bank_msgs, 0);

