// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file modules/crypto/secp256k1.proto (package supabase_l2_blockchain.modules.crypto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/crypto/secp256k1.proto.
 */
export const file_modules_crypto_secp256k1: GenFile = /*@__PURE__*/
  fileDesc("Ch5tb2R1bGVzL2NyeXB0by9zZWNwMjU2azEucHJvdG8SKHN1cGFiYXNlX2wyX2Jsb2NrY2hhaW4ubW9kdWxlcy5jcnlwdG8udjEiJAoTUHJpdmF0ZUtleVNlY3AyNTZrMRINCgV2YWx1ZRgBIAEoDCIjChJQdWJsaWNLZXlTZWNwMjU2azESDQoFdmFsdWUYASABKAxiBnByb3RvMw");

/**
 * @generated from message supabase_l2_blockchain.modules.crypto.v1.PrivateKeySecp256k1
 */
export type PrivateKeySecp256k1 = Message<"supabase_l2_blockchain.modules.crypto.v1.PrivateKeySecp256k1"> & {
  /**
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message supabase_l2_blockchain.modules.crypto.v1.PrivateKeySecp256k1.
 * Use `create(PrivateKeySecp256k1Schema)` to create a new message.
 */
export const PrivateKeySecp256k1Schema: GenMessage<PrivateKeySecp256k1> = /*@__PURE__*/
  messageDesc(file_modules_crypto_secp256k1, 0);

/**
 * @generated from message supabase_l2_blockchain.modules.crypto.v1.PublicKeySecp256k1
 */
export type PublicKeySecp256k1 = Message<"supabase_l2_blockchain.modules.crypto.v1.PublicKeySecp256k1"> & {
  /**
   * @generated from field: bytes value = 1;
   */
  value: Uint8Array;
};

/**
 * Describes the message supabase_l2_blockchain.modules.crypto.v1.PublicKeySecp256k1.
 * Use `create(PublicKeySecp256k1Schema)` to create a new message.
 */
export const PublicKeySecp256k1Schema: GenMessage<PublicKeySecp256k1> = /*@__PURE__*/
  messageDesc(file_modules_crypto_secp256k1, 1);

