// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file modules/crypto/genesis.proto (package supabase_l2_blockchain.modules.crypto.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file modules/crypto/genesis.proto.
 */
export const file_modules_crypto_genesis: GenFile = /*@__PURE__*/
  fileDesc("Chxtb2R1bGVzL2NyeXB0by9nZW5lc2lzLnByb3RvEihzdXBhYmFzZV9sMl9ibG9ja2NoYWluLm1vZHVsZXMuY3J5cHRvLnYxIg4KDEdlbmVzaXNTdGF0ZWIGcHJvdG8z");

/**
 * @generated from message supabase_l2_blockchain.modules.crypto.v1.GenesisState
 */
export type GenesisState = Message<"supabase_l2_blockchain.modules.crypto.v1.GenesisState"> & {
};

/**
 * Describes the message supabase_l2_blockchain.modules.crypto.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_modules_crypto_genesis, 0);

