// @generated by protoc-gen-es v2.2.2 with parameter "target=ts"
// @generated from file core/tx.proto (package supabase_l2_blockchain.core.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file core/tx.proto.
 */
export const file_core_tx: GenFile = /*@__PURE__*/
  fileDesc("Cg1jb3JlL3R4LnByb3RvEh5zdXBhYmFzZV9sMl9ibG9ja2NoYWluLmNvcmUudjEicQoGVHhCb2R5EiIKBG1zZ3MYASADKAsyFC5nb29nbGUucHJvdG9idWYuQW55EgwKBG1lbW8YAiABKAkSNQoRdGltZW91dF90aW1lc3RhbXAYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wIkgKClNpZ25lckluZm8SKAoKcHVibGljX2tleRgBIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSEAoIc2VxdWVuY2UYAiABKAMiTAoIQXV0aEluZm8SQAoMc2lnbmVyX2luZm9zGAEgAygLMiouc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5jb3JlLnYxLlNpZ25lckluZm8iiwEKAlR4EjQKBGJvZHkYASABKAsyJi5zdXBhYmFzZV9sMl9ibG9ja2NoYWluLmNvcmUudjEuVHhCb2R5EjsKCWF1dGhfaW5mbxgCIAEoCzIoLnN1cGFiYXNlX2wyX2Jsb2NrY2hhaW4uY29yZS52MS5BdXRoSW5mbxISCgpzaWduYXR1cmVzGAMgAygMImUKCVR4U2lnbkRvYxI0CgRib2R5GAEgASgLMiYuc3VwYWJhc2VfbDJfYmxvY2tjaGFpbi5jb3JlLnYxLlR4Qm9keRIQCghjaGFpbl9pZBgCIAEoCRIQCghzZXF1ZW5jZRgDIAEoA2IGcHJvdG8z", [file_google_protobuf_any, file_google_protobuf_timestamp]);

/**
 * @generated from message supabase_l2_blockchain.core.v1.TxBody
 */
export type TxBody = Message<"supabase_l2_blockchain.core.v1.TxBody"> & {
  /**
   * @generated from field: repeated google.protobuf.Any msgs = 1;
   */
  msgs: Any[];

  /**
   * @generated from field: string memo = 2;
   */
  memo: string;

  /**
   * @generated from field: google.protobuf.Timestamp timeout_timestamp = 3;
   */
  timeoutTimestamp?: Timestamp;
};

/**
 * Describes the message supabase_l2_blockchain.core.v1.TxBody.
 * Use `create(TxBodySchema)` to create a new message.
 */
export const TxBodySchema: GenMessage<TxBody> = /*@__PURE__*/
  messageDesc(file_core_tx, 0);

/**
 * @generated from message supabase_l2_blockchain.core.v1.SignerInfo
 */
export type SignerInfo = Message<"supabase_l2_blockchain.core.v1.SignerInfo"> & {
  /**
   * @generated from field: google.protobuf.Any public_key = 1;
   */
  publicKey?: Any;

  /**
   * @generated from field: int64 sequence = 2;
   */
  sequence: bigint;
};

/**
 * Describes the message supabase_l2_blockchain.core.v1.SignerInfo.
 * Use `create(SignerInfoSchema)` to create a new message.
 */
export const SignerInfoSchema: GenMessage<SignerInfo> = /*@__PURE__*/
  messageDesc(file_core_tx, 1);

/**
 * @generated from message supabase_l2_blockchain.core.v1.AuthInfo
 */
export type AuthInfo = Message<"supabase_l2_blockchain.core.v1.AuthInfo"> & {
  /**
   * @generated from field: repeated supabase_l2_blockchain.core.v1.SignerInfo signer_infos = 1;
   */
  signerInfos: SignerInfo[];
};

/**
 * Describes the message supabase_l2_blockchain.core.v1.AuthInfo.
 * Use `create(AuthInfoSchema)` to create a new message.
 */
export const AuthInfoSchema: GenMessage<AuthInfo> = /*@__PURE__*/
  messageDesc(file_core_tx, 2);

/**
 * @generated from message supabase_l2_blockchain.core.v1.Tx
 */
export type Tx = Message<"supabase_l2_blockchain.core.v1.Tx"> & {
  /**
   * @generated from field: supabase_l2_blockchain.core.v1.TxBody body = 1;
   */
  body?: TxBody;

  /**
   * @generated from field: supabase_l2_blockchain.core.v1.AuthInfo auth_info = 2;
   */
  authInfo?: AuthInfo;

  /**
   * @generated from field: repeated bytes signatures = 3;
   */
  signatures: Uint8Array[];
};

/**
 * Describes the message supabase_l2_blockchain.core.v1.Tx.
 * Use `create(TxSchema)` to create a new message.
 */
export const TxSchema: GenMessage<Tx> = /*@__PURE__*/
  messageDesc(file_core_tx, 3);

/**
 * @generated from message supabase_l2_blockchain.core.v1.TxSignDoc
 */
export type TxSignDoc = Message<"supabase_l2_blockchain.core.v1.TxSignDoc"> & {
  /**
   * @generated from field: supabase_l2_blockchain.core.v1.TxBody body = 1;
   */
  body?: TxBody;

  /**
   * @generated from field: string chain_id = 2;
   */
  chainId: string;

  /**
   * @generated from field: int64 sequence = 3;
   */
  sequence: bigint;
};

/**
 * Describes the message supabase_l2_blockchain.core.v1.TxSignDoc.
 * Use `create(TxSignDocSchema)` to create a new message.
 */
export const TxSignDocSchema: GenMessage<TxSignDoc> = /*@__PURE__*/
  messageDesc(file_core_tx, 4);

